services:
  # usar cuando se haga la separacion de contenedores
  gestcoop_apache:
    image: httpd:2.4
    container_name: gestcoop_apache
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./public:/var/www/public

      # - ./certs:/etc/apache2/certs
      # - ./docker/apache/default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf

      - ./docker/apache/apache.conf:/usr/local/apache2/conf/extra/apache-custom.conf
      - ./docker/apache/gestcoop.conf:/usr/local/apache2/conf/extra/gestcoop.conf
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf

    # command: >
    #   /bin/bash -c "echo 'Include conf/extra/httpd-ssl.conf' >> /usr/local/apache2/conf/httpd.conf && httpd-foreground"

    depends_on:
      - gestcoop_php

    logging:
      driver: syslog
      options:
        syslog-address: "udp://syslog-server:514" #cambiar a tcp en prod
        tag: "gestcoop_apache"

    networks:
      - app-network
      #Se intenta implementar el sistema de logs
      - logs-net

  gestcoop_php:
    build:
      context: ./docker/php
      dockerfile: dockerfile
    container_name: gestcoop_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./storage/uploads:/var/www/storage/uploads
      - ./vendor:/var/www/vendor
    depends_on:
      - gestcoop_db
    env_file:
      - .env

    logging:
      driver: syslog
      options:
        syslog-address: "udp://syslog-server:514" #cambiar a tcp en prod
        tag: "gestcoop_php"

    networks:
      - app-network
      - logs-net

  gestcoop_db:
    image: mysql:8.0
    container_name: gestcoop_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306" #solo para usar workbench y otros
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql

    logging:
      driver: syslog
      options:
        syslog-address: "udp://syslog-server:514" #cambiar a tcp en prod
        tag: "gestcoop_db"

    networks:
      - app-network
      - logs-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure:5
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - app-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: on-failure:5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

    networks:
      - app-network
      # cadvisor (aun no se sabe si se usara realmente en el proyecto)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: on-failure:5
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  rsync:
    build:
      context: ./docker/rsync
      dockerfile: dockerfile
    container_name: rsync
    restart: on-failure:5
    command: tail -f /dev/null
    volumes:
      - ./data:/data
      - ./backups:/backups

    logging:
      driver: syslog
      options:
        syslog-address: "udp://syslog-server:514"
        tag: "rsync"

  syslog:
    image: balabit/syslog-ng:latest # o adiscon/rsyslog si prefieres rsyslog
    container_name: syslog-server
    restart: unless-stopped
    networks:
      - logs-net

    ports:
      - "514:514/udp" # Puerto est√°ndar syslog UDP
      - "514:514/tcp" # Opcional, si quieres TCP
    volumes:
      - ./logs:/var/log/syslog # Carpeta local para guardar logs

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
  logs-net:
    driver: bridge
