services:
  gestcoop_apache:
    image: httpd:2.4
    container_name: gestcoop_apache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public

      # # Funcionalidad a futuro
      # - ./certs:/etc/apache2/certs
      # - ./docker/apache/default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf

      #configuraciones apache
      - ./docker/apache/apache.conf:/usr/local/apache2/conf/extra/apache-custom.conf
      - ./docker/apache/gestcoop.conf:/usr/local/apache2/conf/extra/gestcoop.conf
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      gestcoop_php:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: gestcoop_apache

  gestcoop_php:
    build:
      context: ./docker/php
      dockerfile: dockerfile
    container_name: gestcoop_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./storage/uploads:/var/www/storage/uploads
      - ./vendor:/var/www/vendor
    depends_on:
      gestcoop_db:
        condition: service_started
    env_file:
      - .env
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: gestcoop_php
  gestcoop_db:
    image: mysql:8.0
    container_name: gestcoop_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # expose:
    #   - "3306"
    # ports:
    #   - "127.0.0.1:3306:3306" # Solo accesible desde localhost
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: gestcoop_db
  # Servicios de monitoreo (se pueden activar si se desea)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure:5
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: on-failure:5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network

      # cadvisor (aun no se sabe si se usara realmente en el proyecto)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: on-failure:5
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

  # SERVICIO PARA BACKUPS DE LA BASE DE DATOS Y UPLOADS
  # rsync:
  #   build:
  #     context: ./docker/rsync
  #     dockerfile: dockerfile
  #   container_name: rsync
  #   restart: on-failure:5
  #   volumes:
  #     - ./storage/uploads:/data/uploads
  #     - ./backups:/backups
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     DB_NAME: ${DB_NAME}

  #Servicio para logs centralizados

volumes:
  db_data:
networks:
  app-network:
    driver: bridge
