services:
  Gestcoop-app:
    image: php:8.2-apache
    container_name: gestcoop-app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/html/app
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - gestcoop-network
  Gestcoop-db:
    image: mysql:8.0
    container_name: gestcoop-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cooperativa
      - MYSQL_USER=bluelab2025
      - MYSQL_PASSWORD=bluelab2025
    networks:
      - gestcoop-network

networks:
  gestcoop-network:
    driver: bridge
