services:
  gestcoop_apache:
    image: httpd:2.4
    container_name: gestcoop_apache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      # # Funcionalidad a futuro
      # - ./certs:/etc/apache2/certs
      # - ./docker/apache/default-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      # configuraciones apache
      - ./docker/apache/apache.conf:/usr/local/apache2/conf/extra/apache-custom.conf
      - ./docker/apache/gestcoop.conf:/usr/local/apache2/conf/extra/gestcoop.conf
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      gestcoop_php:
        condition: service_started

  gestcoop_php:
    build:
      context: ./docker/php
      dockerfile: dockerfile
    container_name: gestcoop_php
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./storage/uploads:/var/www/storage/uploads
      - ./vendor:/var/www/vendor
    user: 1000:1000
    depends_on:
      gestcoop_db:
        condition: service_started
    env_file:
      - .env

  gestcoop_db:
    image: mysql:8.0
    container_name: gestcoop_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Montevideo
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/master/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
      - ./docker/db/master/config/:/etc/mysql/conf.d/master.cnf

  gestcoop_db_slave:
    image: mysql:8.0
    container_name: gestcoop_db_slave
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: America/Montevideo
    depends_on:
      gestcoop_db:
        condition: service_started
    volumes:
      - db_data_slave:/var/lib/mysql
      - ./docker/db/slave/config/:/etc/mysql/conf.d
      - ./docker/db/slave/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql

  gestcoop_backup_server:
    build:
      context: ./docker/backup-server
      dockerfile: dockerfile
    container_name: gestcoop_backup_server
    volumes:
      - ./storage/backup-server/data:/data/backups
    ports:
      - "2222:22" # Puerto SSH expuesto al host
    restart: unless-stopped

volumes:
  db_data:
  db_data_slave:
